version: 0.1.0.{build}

platform: Any CPU

configuration:
  - Release
  - Debug
  
before_build:
  nuget restore

branches:
  except:
    - gh-pages

skip_tags: true

os: Visual Studio 2015

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
